blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('articles/', views.IndexView.as_view(), name='index'),
	path('articles/tag/<slug:tag>/', views.TagView.as_view(), name='by-tag'),
	path('articles/<slug:slug>/', views.DetailView.as_view(), name='detail'),
	# path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	# path('<int:question_id>/vote/', views.vote, name='vote'),
]

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [
	path('', views.WorksList.as_view(), name='index'),
]

blog/models.py
import datetime

from django.db import models
from django.utils import timezone
from slugify import slugify


class Tag(models.Model):
	name = models.CharField('Тэг', max_length=255, null=False, unique=True)
	slug = models.SlugField(unique=True, blank=True, null=False)

	class Meta:
		verbose_name = "Тег"
		verbose_name_plural = "Теги"

	def __str__(self):
		return self.name

	def _get_unique_slug(self):
		slug_max_size = 50
		slug = slugify(self.name)[:slug_max_size]
		unique_slug = slug
		num = 1

		while Tag.objects.filter(slug=unique_slug).exists():
			postfix_size = len(str(num)) + 1
			unique_slug = '{}-{}'.format(
				slug[:(slug_max_size - postfix_size)], num
			)
			num += 1

		return unique_slug

	def save(self, *args, **kwargs):

		if not self.slug:
			self.slug = self._get_unique_slug()

		super().save(*args, **kwargs)


class Article(models.Model):
	title = models.CharField(
		'Заголовок', max_length=255, unique=True, null=False
	)
	slug = models.SlugField(unique=True, null=False, blank=True)
	body = models.TextField('Текст', null=False)
	preview = models.TextField('Превью', null=False)
	created_at = models.DateTimeField('Создана', blank=True)
	pub_date = models.DateTimeField('Дата публикации', blank=True)
	tags = models.ManyToManyField(Tag, verbose_name='Теги')

	def __str__(self):
		return self.title

	def _get_unique_slug(self):
		slug_max_size = 50
		slug = slugify(self.title)[:slug_max_size]
		unique_slug = slug
		num = 1

		while Article.objects.filter(slug=unique_slug).exists():
			postfix_size = len(str(num)) + 1
			unique_slug = '{}-{}'.format(
				slug[:(slug_max_size - postfix_size)], num
			)
			num += 1

		return unique_slug

	def was_published_recently(self):
		now = timezone.now()
		# noinspection PyTypeChecker
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Опубликовано недавно?'

	class Meta:
		verbose_name = "Пост"
		verbose_name_plural = "Посты"

	def save(self, *args, **kwargs):

		if not self.slug:
			self.slug = self._get_unique_slug()

		if self.pk is None:
			if self.created_at is None:
				self.created_at = timezone.now()

			if self.pub_date is None:
				self.pub_date = timezone.now()

		super().save(*args, **kwargs)


class Comment(models.Model):
	body = models.TextField('Текст', null=False)
	nickname = models.CharField('Ник', null=False, max_length=255)
	datetime = models.DateTimeField('Дата', null=False, blank=True)
	article = models.ForeignKey(
		'Article', on_delete=models.CASCADE, null=False
	)

	def save(self, *args, **kwargs):

		if self.pk is None:
			if self.datetime is None:
				self.datetime = timezone.now()

		super().save(*args, **kwargs)

	class Meta:
		verbose_name = "Комментарий"
		verbose_name_plural = "Комментарии"

portfolio/models.py
from django.db import models
from django.utils.text import slugify
from django_s3_storage.storage import S3Storage

from blog.models import Tag

storage = S3Storage(aws_s3_bucket_name='codocalypse')


class Work(models.Model):
	name = models.CharField(
		'Название', max_length=255, null=False, default='', unique=True
	)
	url = models.URLField()
	url_source = models.URLField('URL исходников', null=True)
	short_description = models.TextField('Краткое описание', max_length=63)
	description = models.TextField('Описание')
	image = models.ImageField('Изображение', storage=storage, upload_to='works')
	slug = models.SlugField(null=False, default='', unique=True, blank=True)

	tags = models.ManyToManyField(Tag, verbose_name='Теги')

	created_at = models.DateTimeField('Создано', auto_now_add=True)
	updated_at = models.DateTimeField('Изменено', auto_now=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Работа"
		verbose_name_plural = "Работы"

	def _get_unique_slug(self, slug_max_length=50):
		slug_max_size = slug_max_length
		slug = slugify(self.name, allow_unicode=True)[:slug_max_size]
		unique_slug = slug
		num = 1

		while Work.objects.filter(slug=unique_slug).exists():
			# обрезаем размер слага, чтобы он влез в поле
			postfix_size = len(str(num)) + 1
			unique_slug = '{}-{}'.format(
				slug[:(slug_max_size - postfix_size)], num
			)
			num += 1

		return unique_slug

	def save(self, *args, **kwargs):
		self.slug = self._get_unique_slug()

		super().save(*args, **kwargs)

blog/views.py
from django.views import generic
from .models import Article


class IndexView(generic.ListView):
	model = Article
	paginate_by = 10
	ordering = ['-pk']


class TagView(IndexView):
	def get_queryset(self):
		return Article.objects.filter(tags__slug__contains=self.kwargs['tag'])


class DetailView(generic.DetailView):
	model = Article
	article = None

	def get_queryset(self):
		self.article = Article.objects.filter(slug=self.kwargs['slug'])
		return self.article

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['comments'] = self.article.get().comment_set.order_by(
			'datetime'
		).all()
		return context

chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json


def index(request):
	return render(request, 'chat/index.html', {})


def room(request, room_name):
	return render(request, 'chat/room.html', {
		'room_name_json': mark_safe(json.dumps(room_name))
	})

portfolio/views.py
from django.shortcuts import render
from django.views.generic import ListView

from portfolio.models import Work


def index(request):
	return render(request, 'portfolio/work_list.html')


class WorksList(ListView):
	model = Work

blog/templates/base.html
{% load main_menu %}
<!doctype html>
<html lang="ru">
<head>
  {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'floating-labels.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar fixed-bottom navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Codocalypse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbar">
    {% main_menu request %}
    <form class="form-inline my-2 my-md-0">
      <input class="form-control" type="text" placeholder="Поиск">
    </form>
  </div>
</nav>
<div class="{% block container_class %}container{% endblock %}">
  <section class="content">
    <header>
      {% block header %}{% endblock %}
    </header>
    {% block content %}{% endblock %}
  </section>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/article_detail.html
{% extends "base.html" %}

{% block header %}<h1>{% block title %}{{ article.title }}{% endblock %}</h1>{% endblock %}

{% block content %}
  <section class="article-detail">
    <header class="article-detail__header row justify-content-between align-items-baseline">
      <small class="article-detail__time text-muted col-auto">
        {{ article.pub_date|date:"DATETIME_FORMAT" }}
      </small>
    </header>

    <p class="article-detail__body">{{ article.body }}</p>
    <footer class="article-footer row justify-content-space-between">
      <div class="article-detail__tags-list col order-last order-sm-first">
        {% for tag in article.tags.all %}
          <a href="{% url 'blog:by-tag' tag=tag.slug %}">{{ tag.name }}</a>
        {% endfor %}
      </div>
    </footer>

  </section>

  <section class="comments">
    <h2 class="comments__title">Комментарии</h2>
    <div class="comments__list" id="commentsList">
      {% for comment in comments %}
        <article class="comment">
        <header class="comment__header row justify-content-between align-items-baseline">
          <h4 class="comment__author col">{{ comment.nickname }}</h4>
          <small class="comment__time text-muted col-auto">{{ comment.datetime|date:"DATETIME_FORMAT" }}</small>
        </header>

        <div class="comment__body">{{ comment.body }}</div>
      </article>
      {% endfor %}
    </div>
    <div class="comments__form">
      <div class="form-label-group">
        <input type="text" id="chat-message-nickname" class="form-control" placeholder="Ваш ник" required="">
        <label for="chat-message-nickname">Ваш ник</label>
      </div>
      <div class="form-label-group">
        <input type="text" id="chat-message-input" class="form-control" placeholder="Сообщение" required="">
        <label for="chat-message-input">Сообщение</label>
      </div>
      <input id="chat-message-submit" type="button" class="btn btn-primary" value="Отправить"/>
    </div>
  </section>

  <!--suppress JSUnusedLocalSymbols -->
  <script>
    let roomName = '{{ article.slug }}';
    let articlePk = '{{ article.pk }}';

    let chatSocket = new WebSocket(
      'wss://' + window.location.host +
      '/ws/articles/' + roomName + '/');

    function getDateString(datetime){
      datetime = new Date(datetime);
      const date = datetime.toLocaleDateString();

      let strDatetime = datetime.toLocaleTimeString().slice(0, -3);

      if(date !== new Date().toLocaleDateString()){
        strDatetime = date + ' ' + strDatetime
      }

      return strDatetime
    }

    function appendMessage(message, nickname, datetime) {
      let commentsList = $("#commentsList");

      datetime = getDateString(datetime);

      let newComment = $(
        "<article class=\"comment\">\n" +
        "    <header class=\"comment__header row justify-content-between align-items-baseline\">\n" +
        "         <h4 class=\"comment__author col\">" + nickname + "</h4>\n" +
        "         <small class=\"comment__time text-muted col-auto\">" + datetime + "</small>\n" +
        "    </header>\n" +
        "    <div class=\"comment__body\">" + message + "</div>\n" +
        "</article>"
      );

      commentsList.append(newComment)
    }

    chatSocket.onmessage = function (e) {
      let data = JSON.parse(e.data);
      let message = data['message'];
      let nickname = data['nickname'];
      let datetime = data['datetime'];

      appendMessage(message, nickname, datetime)
    };

    chatSocket.onclose = function (e) {
      console.error('Chat socket closed unexpectedly');
      console.error(e)
    };

    let inputMessage = document.querySelector('#chat-message-input');
    let inputNickname = document.querySelector('#chat-message-nickname');
    let submit = document.querySelector('#chat-message-submit');

    inputMessage.onkeyup = function (e) {
      if (e.keyCode === 13) {  // enter, return
        submit.click();
      }
    };

    submit.onclick = function (e) {
      let messageInputDom = inputMessage;
      let nicknameInputDom = inputNickname;

      let message = messageInputDom.value;
      let nickname = nicknameInputDom.value;
      console.log({
        'message': message,
        'nickname': nickname,
        'datetime': new Date().toJSON(),
        'articlePk': articlePk
      });
      chatSocket.send(JSON.stringify({
        'message': message,
        'nickname': nickname,
        'datetime': new Date().toJSON(),
        'articlePk': articlePk
      }));

      messageInputDom.value = '';
    };
  </script>
{% endblock %}

blog/templates/blog/article_list.html
{% extends "base.html" %}

{% block header %}<h1>{% block title %}Блог{% endblock %}</h1>{% endblock %}

{% block content %}
  <div class="row">
    {% for article in page_obj %}
      <div class="col-12">
        <article class="article">
          <header class="article__header row justify-content-between align-items-baseline">
            <h2 class="article__title col">{{ article.title }}</h2>
{#            <h2 class="article__title col-auto" style="display: inline-block">{% lorem 2 w %}</h2>#}
            <small class="article__time text-muted col-auto">
              {{ article.pub_date|date:"DATETIME_FORMAT" }}
            </small>
          </header>

          <p class="article__preview">{{ article.preview }}</p>
{#          <p class="article__preview">{% lorem 1 %}</p>#}
          <footer class="article-footer row justify-content-space-between">
            <div class="article__tags-list col order-last order-sm-first">
              {% for tag in article.tags.all %}
                <a href="{% url 'blog:by-tag' tag=tag.slug %}">{{ tag.name }}</a>
              {% endfor %}
            </div>
            <div class="col col-12 col-sm-auto order-first order-sm-last">
              <a href="{% url 'blog:detail' slug=article.slug %}"
                 class="article__read-more btn btn-sm btn-outline-primary col">Читать далее →</a>
            </div>
          </footer>

        </article>
      </div>
    {% endfor %}
  </div>

  {% if is_paginated %}
    <hr>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
          {% else %}
            <!-- Append the searched query to the URL, so that on a search results page,
                 the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="?{{ search }}&page={{ page_obj.previous_page_number }}"
                 tabindex="-1">Previous</a>
            </li>
          {% endif %}
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="javascript:void(0);" tabindex="-1">Назад</a>
          </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
          <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          {% if not search %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперёд</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?{{ search }}&page={{ page_obj.next_page_number }}">Вперёд</a>
            </li>
          {% endif %}
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="javascript:void(0);">Вперёд</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}

{% endblock %}

blog/templates/main_menu.html
<ul class="navbar-nav mr-auto">
  {% for title, url, active in items %}
    <li class="nav-item{% if active %} active{% endif %}">
      <a class="nav-link" href="{{ url }}">{{ title }}{% if active %}
        <span class="sr-only">(текущая)</span>
      {% endif %}
      </a>
    </li>
  {% endfor %}
</ul>

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<!--suppress HtmlFormInputWithoutLabel -->
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <!--suppress JSUnusedLocalSymbols -->
    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<!--suppress HtmlFormInputWithoutLabel -->
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<!--suppress JSUnusedAssignment, JSUnusedLocalSymbols, ES6ConvertVarToLetConst -->
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

portfolio/templates/portfolio/work_index.html
{% extends "base.html" %}

{% block header %}<h1>{% block title %}Портфолио{% endblock %}</h1>{% endblock %}

{% block content %}

  портфолио

{% endblock %}

portfolio/templates/portfolio/work_list.html
{% extends "base.html" %}

{% block header %}<h1>{% block title %}Портфолио{% endblock %}</h1>{% endblock %}

{% block content %}

  <div class="row works-list">
    {% for work in object_list %}
      <div class="col-xs-12 col-sm-4 col-lg-3 work">
        <a href="#" class="work__link">
          <div class="work__img" style="background-image: url('{{ work.image.url }}')"></div>
          <div class="work__title">
            <h2>{{ work.name }}</h2>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>


{% endblock %}